/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "krbaxodmlraiwkqbjuyw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyYmF4b2RtbHJhaXdrcWJqdXl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMzE2NTgsImV4cCI6MjA3MTgwNzY1OH0.44Oggv2BLKEG2NzpNb5w1ija4v-_4_t4EXVj3wl_yQY"